# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main


schedules:
  - cron: "36 20 * * 0"
    displayName: "Started with Timer!"
    always: true
    branches:
      include : 
        - master

stages:
  - stage: 
    displayName: "Puppeteer Stage"
    jobs:
      - job:
#        pool:
#          vmImage: 'windows-latest'
        displayName: "Test job"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '6.x'
              checkLatest: true
          - task: Npm@1
            inputs:
              command: 'install'
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'install puppeteer'
          - script: |
              npm i puppeteer
              node puppeteer_test2.js 2 015778442307 john.iskander@gmx.de John Iskander Jackline Tawadros
            displayName: 'Run a multi-line script'
  
