# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main


schedules:
  - cron: "36 20 * * 0"
    displayName: "Started with Timer!"
    always: true
    branches:
      include : 
        - master

stages:
  - stage: 
    displayName: "Puppeteer Stage"
    jobs:
      - job:
#        pool:
#          vmImage: 'windows-latest'
        displayName: "Puppeteer job"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
              checkLatest: true
          - task: Npm@1
            inputs:
              command: 'install'

          - script: |
              npm install --save-dev puppeteer
            displayName: 'Install Puppeteer'
          - script: |    
              mkdir WebApp
              node puppeteer_test.js $(numberOfAttendees) $(telephoneNumber) $(emailAddress) $(user1FN) $(user1LN) $(user2FN) $(user2LN)
            displayName: 'John - Run booking puppeteer script'
            continueOnError: true 
          - script: |    
              node puppeteer_test.js 2 015786178127 niantoni94@web.de Nico Antoni Saskia Alber
            displayName: 'Nico - Run booking puppeteer script'
            continueOnError: true
          - script: |    
              ls
            displayName: 'list all files'
            continueOnError: true
          - task: CopyFiles@2
            inputs:
              Contents: '*.pdf'
              TargetFolder: 'WebApp'
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: ./WebApp
              artifactName: drop
  
