# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main


schedules:
  - cron: "36 20 * * 0"
    displayName: "Started with Timer!"
    always: true
    branches:
      include : 
        - master

stages:
  - stage: 
    displayName: "Puppeteer Stage"
    jobs:
      - job:
#        pool:
#          vmImage: 'windows-latest'
        displayName: "Puppeteer job"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
              checkLatest: true
          - task: Npm@1
            inputs:
              command: 'install'

          - script: |
              npm install --save-dev puppeteer
            displayName: 'Install Puppeteer'
          - script: |    
              mkdir WebApp
              node puppeteer_test.js 2 $(telephoneNumber) $(emailAddress) $(user1FN) $(user1LN) $(user2FN) $(user2LN) Ruben Platia Mareike Platia Lukas Gesell Celine Stieber Eliane David David Eliane 
            displayName: 'John - Run booking puppeteer script'
            continueOnError: true 
          - script: |    
              node puppeteer_test.js 2 $(telephoneNumber2) $(emailAddress2) $(user3FN) $(user3LN) $(user4FN) $(user4LN) Chris Voige Ophelie Vernet
            displayName: 'Nico - Run booking puppeteer script'
            continueOnError: true
          - script: |    
              node puppeteer_test.js 2 $(telephoneNumber3) $(emailAddress3) $(user11FN) $(user11LN) $(user12FN) $(user12LN) 
            displayName: 'Ruben - Run booking puppeteer script'
            continueOnError: true    
          - script: |    
              node puppeteer_test.js 2 $(telephoneNumber4) $(emailAddress4) $(user5FN) $(user5LN) $(user6FN) $(user6LN) 
            displayName: 'Lukas - Run booking puppeteer script'
            continueOnError: true              
          - script: |    
              node puppeteer_test.js 1 $(telephoneNumber6) $(emailAddress6) $(user9FN) $(user9LN)
            displayName: 'Chris - Run booking puppeteer script'
            continueOnError: true     
          - script: |    
              node puppeteer_test.js 1 $(telephoneNumber7) $(emailAddress7) $(user10FN) $(user10LN)
            displayName: 'Ophelie - Run booking puppeteer script'
            continueOnError: true     
          - script: |    
              ls
            displayName: 'list all files'
            continueOnError: true
          - task: CopyFiles@2
            inputs:
              Contents: '*.pdf'
              TargetFolder: 'WebApp'
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: ./WebApp
              artifactName: drop
  
