# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main


schedules:
  - cron: "36 20 * * 0"
    displayName: "Started with Timer!"
    always: true
    branches:
      include : 
        - master

stages:
  - stage: 
    displayName: "Puppeteer Stage"
    jobs:
      - job:
#        pool:
#          vmImage: 'windows-latest'
        displayName: "Puppeteer job"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
              checkLatest: true
          - task: Npm@1
            inputs:
              command: 'install'

          - script: |
              npm install --save-dev puppeteer
            displayName: 'Install Puppeteer'
          - script: |    
              mkdir WebApp
              node puppeteer_test2.js 2 015778442307 john.iskander@gmx.de John Iskander Jackline Tawadros
            displayName: 'Run booking puppeteer script'
          - script: |    
              ls
            displayName: 'list all files'
          - download: current
            artifact: WebApp
            patterns: '**'
  
